language: python
sudo: false
cache:
    directories:
        - $HOME/.cache/pip

matrix:
    include:
        - python: 2.7
          env: TOXENV=py27

script: travis_scripts/run_tests.sh

after_success:
  - coverage combine .coverage_data
  - codecov